### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by ShintaroNippon** [featurist/jquery-sendkeys#3]
Hi there...

Hi have this code 

```
var $ = require('jquery');
require('jquery-sendkeys');

$('#email-3').sendkeys('carlos@gmail.com');
```

but when i'm running the tests like node happy_trail.js
i'm getting this error

/private/var/local/www/site/node_modules/jquery-sendkeys/bililiteRange.js:30
var focusEvent = 'onfocusin' in document.createElement('input') ? 'focusin' : 'focus';
                                ^

```
ReferenceError: document is not defined
    at /private/var/local/www/site/node_modules/jquery-sendkeys/bililiteRange.js:30:33
    at Object.<anonymous> (/private/var/local/www/site/node_modules/jquery-sendkeys/bililiteRange.js:738:3)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/private/var/local/www/site/node_modules/jquery-sendkeys/index.js:29:21)

```

Do you know anything about to resolve this...
i have installed the lastest version of jquery... as npm install
i'm trying to implementing some test selenium code

many thanks
carlos vieira

**Comment by btm1** [comment]
Bump... I'm getting the same error. Any solution here?

**Comment by refractalize** [comment]
hi @btm1 are you running this in Node, or in the browser?

**Comment by JohnMcLear** [comment]
looks like they think this is a node module, it is not...  Closable?
